#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: phpize
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : php-mongodb
Version  : 1.21.0
Release  : 117
URL      : https://pecl.php.net/get/mongodb-1.21.0.tgz
Source0  : https://pecl.php.net/get/mongodb-1.21.0.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: php-mongodb-lib = %{version}-%{release}
Requires: php-mongodb-license = %{version}-%{release}
BuildRequires : buildreq-php
BuildRequires : cyrus-sasl-dev
BuildRequires : file
BuildRequires : openssl-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : zlib-dev
BuildRequires : zstd-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# MongoDB PHP Driver
[![Tests](https://github.com/mongodb/mongo-php-driver/actions/workflows/tests.yml/badge.svg)](https://github.com/mongodb/mongo-php-driver/actions/workflows/tests.yml)
[![Coverage Status](https://coveralls.io/repos/github/mongodb/mongo-php-driver/badge.svg?branch=master)](https://coveralls.io/github/mongodb/mongo-php-driver?branch=master)
[![Coding Standards](https://github.com/mongodb/mongo-php-driver/actions/workflows/clang-format.yml/badge.svg)](https://github.com/mongodb/mongo-php-driver/actions/workflows/clang-format.yml)

%package lib
Summary: lib components for the php-mongodb package.
Group: Libraries
Requires: php-mongodb-license = %{version}-%{release}

%description lib
lib components for the php-mongodb package.


%package license
Summary: license components for the php-mongodb package.
Group: Default

%description license
license components for the php-mongodb package.


%prep
%setup -q -n mongodb-1.21.0
cd %{_builddir}/mongodb-1.21.0
pushd ..
cp -a mongodb-1.21.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure --disable-static
make  %{?_smp_mflags}

%install
mkdir -p %{buildroot}/usr/share/package-licenses/php-mongodb
cp %{_builddir}/mongodb-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/php-mongodb/5a7d7df655ba40478fae80a6abafc6afc36f9b6a || :
%make_install

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20240924/mongodb.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/php-mongodb/5a7d7df655ba40478fae80a6abafc6afc36f9b6a
