#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-mongodb
Version  : 1.14.0
Release  : 41
URL      : https://pecl.php.net/get/mongodb-1.14.0.tgz
Source0  : https://pecl.php.net/get/mongodb-1.14.0.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: php-mongodb-lib = %{version}-%{release}
BuildRequires : buildreq-php
BuildRequires : cyrus-sasl-dev
BuildRequires : openssl-dev
BuildRequires : pcre2-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : zstd-dev

%description
# MongoDB PHP Driver
[![Tests](https://github.com/mongodb/mongo-php-driver/actions/workflows/tests.yml/badge.svg)](https://github.com/mongodb/mongo-php-driver/actions/workflows/tests.yml)
[![AppVeyor Build Status](https://ci.appveyor.com/api/projects/status/gbd3t99ucib5n8sf?svg=true)](https://ci.appveyor.com/project/jmikola/mongo-php-driver)
[![Coverage Status](https://coveralls.io/repos/github/mongodb/mongo-php-driver/badge.svg?branch=master)](https://coveralls.io/github/mongodb/mongo-php-driver?branch=master)
[![Coding Standards](https://github.com/mongodb/mongo-php-driver/actions/workflows/clang-format.yml/badge.svg)](https://github.com/mongodb/mongo-php-driver/actions/workflows/clang-format.yml)

%package lib
Summary: lib components for the php-mongodb package.
Group: Libraries

%description lib
lib components for the php-mongodb package.


%prep
%setup -q -n mongodb-1.14.0
cd %{_builddir}/mongodb-1.14.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure --disable-static
make  %{?_smp_mflags}

%install
%make_install


%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20210902/mongodb.so
